apiVersion: v1
kind: Service
metadata:
  name: ciudapp-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ciudapp-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciudapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ciudapp-frontend
  template:
    metadata:
      labels:
        app: ciudapp-frontend
    spec:
      containers:
      - name: ciudapp-frontend
        image: rlsanjose/ciudapp-frontend-cloud:2.1
        ports:
        - containerPort: 8080

